### PR TITLE
fix(1.6): convert occurrences of OrganizationalEntity

### LINKED ISSUE #174: Convert `OrganizationalEntity` to legacy spec versions
In #173, a new type `PostalAddress` is being added to the `OrganizationalEntity` type. Organizational entities are being referenced in many locations of the spec and must all be handled individually when converting to a spec version lower than 1.6.

### PR DESCRIPTION
**Pull request by mcombuechen**
This adds `func convertOrganizationalEntity()` and targets occurences of `OrganizationalEntity` during spec conversion. This is an addendum to #173.

Closes #174.

### CODE REVIEW

File: convert.go [hunk 1]
```diff
@@ -316,6 +344,16 @@ func convertVulnerabilities(vulns *[]Vulnerability, specVersion SpecVersion) {
 			vuln.Workaround = ""
 		}
 
+		if specVersion < SpecVersion1_6 {
+			if vuln.Credits != nil {
+				if vuln.Credits.Organizations != nil {
```
Comment (mcombuechen) [inline convert.go:349]: Not too happy about all the nested `if`s, but wanted to avoid `&&`. Let me know what you think.

**Review by nscuro — APPROVED** [review]
